### PR TITLE
Fix crash on AudioEngine destruction

### LINKED ISSUE #37: Audio Engine causes a crash on exit
When copied, the AudioEngine object does not move its internal openAL handles causing a crash as they are being double freed on destruction.

### PR DESCRIPTION
**Pull request by NoOverflow**
Fixes #37

### CODE REVIEW

File: ige/src/plugin/audio/AudioEngine.cpp [hunk 1]
```diff
@@ -3,6 +3,7 @@
 #include <AL/al.h>
 #include <AL/alc.h>
 #include <cstring>
+#include <iostream>
```
Comment (nasso) [inline ige/src/plugin/audio/AudioEngine.cpp]: ?

File: ige/src/plugin/audio/AudioEngine.cpp [hunk 2]
```diff
@@ -32,8 +33,23 @@ AudioEngine::AudioEngine(const char* deviceName)
     AudioEngine::get_native_exception();
 }
 
+AudioEngine::AudioEngine(AudioEngine&& engine)
+{
+    *this = std::move(engine);
```
Comment (nasso) [inline ige/src/plugin/audio/AudioEngine.cpp:38]: using the `std::move` function template requires including the `<utility>` standard header

File: ige/src/plugin/audio/AudioEngine.cpp [hunk 3]
```diff
@@ -32,8 +33,23 @@ AudioEngine::AudioEngine(const char* deviceName)
...
+}
+
+AudioEngine& AudioEngine::operator=(AudioEngine&& other)
+{
+    this->m_context = other.m_context;
+    this->m_device = other.m_device;
+    other.m_moved = true;
+    return *this;
+}
```
Comment (nasso) [inline ige/src/plugin/audio/AudioEngine.cpp]: the context that is potentially held by `this` might not be closed here
`this->m_moved` is also never reset if it was set to `true`

File: ige/src/plugin/audio/AudioEngine.cpp [hunk 4]
```diff
@@ -32,8 +33,23 @@ AudioEngine::AudioEngine(const char* deviceName)
...
+
 AudioEngine::~AudioEngine()
 {
+    if (m_moved)
+        return;
     alcMakeContextCurrent(nullptr);
     alcDestroyContext(m_context);
     alcCloseDevice(m_device);
```
Comment (nasso) [inline ige/src/plugin/audio/AudioEngine.cpp]:
```suggestion
    if (!m_moved) {
        alcMakeContextCurrent(nullptr);
        alcDestroyContext(m_context);
        alcCloseDevice(m_device);
    }
```

**Review by nasso — CHANGES_REQUESTED** [review]
